# -*- coding: utf-8 -*-
"""Datos compartidos del documento: 44 HUs del MVP de EAG Ingenieros (SECOP II).

Consumido por build_page.py (diseño propuesta) y build_docs.py (diseño documentación).
Estructura de EPICAS: (codigo, titulo, descripcion, issues, [(id, prioridad, issue, actor, capacidad, valor, [criterios]), ...])
"""

E1 = ("E1", "Acceso, roles y aislamiento",
      "Permitir el uso del sistema solo a personas invitadas, con dos roles y controles efectivos en backend y datos.",
      "MVP-04", [
("HU-01","P0","MVP-04","Usuario invitado","acceder mediante un enlace de autenticación válido","usar el sistema sin registro público ni contraseña gestionada por la aplicación",
 ["El acceso exige una invitación vigente y una sesión válida.",
  "Un token ausente, inválido o vencido recibe 401.",
  "La interfaz no expone registro público ni permite elegir rol u organización."]),
("HU-02","P0","MVP-04","Usuario autenticado","consultar mi sesión y cerrar sesión","confirmar mi identidad, rol y pertenencia antes de trabajar",
 ["La sesión muestra únicamente identidad y pertenencia propias.",
  "El backend valida firma, expiración, issuer y audience configurados.",
  "Tras retirar la membresía, las rutas protegidas dejan de autorizar al usuario; la limitación del TTL del proveedor queda visible."]),
("HU-03","P0","MVP-04","Administrador","crear, revocar y consultar invitaciones de EAG","controlar quién puede ingresar a la organización",
 ["Solo el administrador ejecuta estas acciones desde el backend.",
  "El cliente no puede escoger role ni organization_id en el cuerpo.",
  "Cada acción genera auditoría sin tokens, secretos ni correos en metadata.",
  "El reenvío solo se habilita cuando exista una operación de proveedor comprobada; mientras tanto se informa como no disponible."]),
("HU-04","P0","MVP-04","Administrador","aplicar permisos por rol y recurso","evitar acceso horizontal, escalada de privilegios y exposición entre organizaciones",
 ["Un usuario autenticado sin permiso recibe 403.",
  "El rol y la organización se resuelven en el servidor, no desde claims o campos confiados al navegador.",
  "Las pruebas negativas cubren recursos ajenos, escritura directa y claves privilegiadas en cliente o logs."]),
])

E2 = ("E2", "Oportunidades SECOP II",
      "Incorporar oportunidades oficiales de forma idempotente y facilitar su búsqueda sin inventar cobertura ni datos.",
      "MVP-02 · MVP-05 · MVP-06", [
("HU-05","P0","MVP-02 / MVP-05","Sistema","sincronizar oportunidades desde los conjuntos oficiales verificados","mantener un catálogo trazable a SECOP II",
 ["Cada oportunidad conserva ID, enlace, fuente, campos originales relevantes y fecha de consulta.",
  "La consulta usa filtros permitidos, paginación, timeout, reintentos limitados y manejo de cuota.",
  "Una ejecución de red acotada se distingue de fixtures y mocks."]),
("HU-06","P0","MVP-05","Administrador","ejecutar una sincronización manual autorizada","actualizar el catálogo cuando sea necesario y observar su resultado",
 ["Solo un rol autorizado puede iniciar la operación.",
  "Repetir o reintentar un lote no crea duplicados.",
  "Éxitos parciales, 429, timeouts y registros pendientes quedan visibles y reanudables."]),
("HU-07","P1","MVP-05","Sistema","ejecutar una sincronización periódica incremental","detectar cambios tardíos sin recorrer indiscriminadamente toda la fuente",
 ["Horario, zona horaria y ventana incremental son configurables.",
  "El campo temporal usado corresponde al esquema real verificado.",
  "La propuesta de 06:00 America/Bogota y 7 días no se activa como decisión definitiva sin validación."]),
("HU-08","P0","MVP-06","Analista","listar, ordenar, paginar y filtrar oportunidades","encontrar casos relevantes para revisión",
 ["Filtros y resultados provienen de la API, sin datos mock en producción.",
  "Se muestran carga, vacío, error y datos desactualizados.",
  "Los controles son operables con teclado y en pantalla estrecha."]),
("HU-09","P1","MVP-06","Analista","guardar y reutilizar filtros de trabajo","repetir búsquedas frecuentes con criterios consistentes",
 ["Solo se ofrecen campos disponibles y verificados.",
  "Los filtros personales se distinguen de la configuración compartida.",
  "Solo usuarios autorizados modifican filtros compartidos de EAG."]),
("HU-10","P0","MVP-06","Analista","abrir el detalle de una oportunidad y volver al listado","examinar sus datos oficiales sin perder el contexto de búsqueda",
 ["El detalle muestra ID, enlace oficial, fuente y última sincronización.",
  "Datos ausentes se presentan como desconocidos, no como cero.",
  "Al volver se conservan filtros, orden y página."]),
])

E3 = ("E3", "Expediente documental seguro",
      "Reunir documentos de la oportunidad con controles de seguridad, versiones y faltantes explícitos.",
      "MVP-07", [
("HU-11","P0","MVP-07","Analista","obtener los documentos disponibles desde SECOP II","formar el expediente de la oportunidad con su origen comprobable",
 ["La descarga usa dominios permitidos, timeout, tamaño máximo y redirecciones validadas.",
  "Cada archivo conserva origen, hash, versión, fecha y estado.",
  "Descarga encontrada no se presenta como expediente completo."]),
("HU-12","P0","MVP-07","Analista","cargar documentos complementarios de una oportunidad SECOP II","completar el expediente cuando la fuente oficial no permita obtenerlos",
 ["La carga manual exige oportunidad oficial existente y permiso sobre ella.",
  "Se aceptan inicialmente PDF, DOCX y XLSX válidos; ZIP se rechaza salvo controles seguros explícitos.",
  "El origen manual queda diferenciado del origen SECOP."]),
("HU-13","P0","MVP-07","Sistema","validar y poner en cuarentena cada archivo","impedir que contenido peligroso o simulado avance al procesamiento",
 ["Se validan extensión, firma/MIME, nombre seguro y límites configurables.",
  "Se bloquean ejecutables, macros, path traversal, tipo simulado y SSRF.",
  "Un fallo del antivirus no equivale a archivo limpio; un archivo en cuarentena no se procesa."]),
("HU-14","P0","MVP-07","Usuario autorizado","consultar o descargar documentos privados","revisar evidencia sin exponerla públicamente",
 ["El backend autoriza cada recurso y el almacenamiento permanece privado.",
  "Los enlaces firmados tienen vida breve y no se registran con contenido sensible.",
  "Las pruebas cubren acceso permitido y denegado."]),
("HU-15","P0","MVP-07","Analista","ver el inventario, las versiones y los documentos faltantes","saber si el expediente permite un análisis defendible",
 ["Cada elemento muestra origen, versión, estado de lectura y retención.",
  "Los documentos esperados pero ausentes se registran como faltantes.",
  "Un expediente incompleto limita las conclusiones y no se interpreta como ausencia de requisitos."]),
])

E4 = ("E4", "Extracción de texto y OCR",
      "Convertir archivos aprobados en texto trazable sin ocultar fallos ni mezclar versiones.",
      "MVP-08", [
("HU-16","P0","MVP-08","Sistema","extraer texto de PDF, DOCX y XLSX aprobados","habilitar análisis posterior conservando la estructura de origen",
 ["Fixtures sintéticas por formato producen texto y localizadores verificables.",
  "El proceso respeta límites de páginas, memoria, tiempo y reintentos.",
  "Archivos corruptos, cifrados o fuera de presupuesto terminan con error visible y recuperable."]),
("HU-17","P0","MVP-08","Sistema","aplicar OCR básico cuando un PDF no tenga texto suficiente","recuperar contenido de escaneados sin fingir precisión",
 ["OCR se activa por un criterio explícito y configurable.",
  "El resultado conserva página y advertencias de calidad.",
  "Texto vacío o OCR deficiente pasa a revisión manual, no a éxito silencioso."]),
("HU-18","P0","MVP-08","Analista","consultar estados y advertencias de extracción","identificar qué documento requiere reemplazo, reintento o revisión humana",
 ["Se distinguen pendiente, procesando, completado con advertencias y fallido.",
  "La causa y el siguiente paso se muestran sin contenido sensible en logs.",
  "Un reintento controlado no duplica trabajo completado para el mismo hash y versión."]),
("HU-19","P0","MVP-08","Analista","navegar del texto extraído a su localizador","verificar cada fragmento contra documento, página, sección o celda",
 ["Documento, localizador y versión acompañan cada fragmento.",
  "El localizador permite comprobación manual en una muestra autorizada.",
  "Reprocesar una versión nueva no modifica silenciosamente resultados anteriores."]),
])

E5 = ("E5", "Perfil y evidencias empresariales",
      "Mantener una fuente empresarial autorizada, versionada y verificable para las comparaciones.",
      "MVP-09", [
("HU-20","P0","MVP-09","Administrador","registrar experiencia y contratos de EAG","sustentar requisitos de experiencia con datos y soportes",
 ["Se registran objeto/especialidad, rol, fechas, valor/moneda cuando aplique y soporte.",
  "Cada evidencia tiene documento, localizador, versión y vigencia o queda pendiente.",
  "Datos desconocidos no se convierten en cero."]),
("HU-21","P0","MVP-09","Administrador","registrar personal y sus credenciales","contrastar perfiles requeridos sin exponer datos innecesarios",
 ["Se incluyen identificador interno, rol, formación, experiencia y certificaciones/vigencias pertinentes.",
  "El acceso sigue la matriz de permisos y minimiza datos personales.",
  "Un perfil incompleto conduce a pendiente o revisión, no a incapacidad definitiva."]),
("HU-22","P0","MVP-09","Administrador","registrar capacidades, equipos y disponibilidad acreditada","evaluar requisitos técnicos y operativos con soporte",
 ["Tipo, cantidad, características y disponibilidad usan unidades explícitas.",
  "La evidencia se marca pendiente o verificada por revisión humana.",
  "Una afirmación sin soporte no puede sustentar un cumple."]),
("HU-23","P0","MVP-09","Administrador","registrar información financiera, legal y documental","comparar indicadores y vigencias exigidos por una oportunidad",
 ["Período, valores, moneda/unidad, fórmula y soporte quedan identificados.",
  "Las fechas y números se validan; vacío, desconocido y cero son distintos.",
  "Solo se exponen los datos necesarios al rol autorizado."]),
("HU-24","P0","MVP-09","Administrador","editar el perfil creando una nueva versión e historial","preservar qué evidencia se usó en cada análisis",
 ["La edición guarda autor, fecha, motivo y estado pendiente/verificado.",
  "Los análisis existentes mantienen referencia a la versión comparada.",
  "La política de retención del perfil maestro se distingue de la de documentos de oportunidad."]),
])

E6 = ("E6", "Extracción estructurada de requisitos",
      "Identificar requisitos mediante un adaptador de IA, conservando evidencia, límites y revisión.",
      "MVP-10", [
("HU-25","P0","MVP-10","Analista","obtener requisitos estructurados del expediente","reducir lectura inicial sin perder categorías, condiciones ni fuente",
 ["La salida cumple un esquema tipado y no decide participación ni cumplimiento final.",
  "Cada requisito incluye categoría, texto, documento, localizador, fragmento y versión.",
  "Salida inválida, truncada o ambigua se rechaza o marca para revisión."]),
("HU-26","P0","MVP-10","Sistema","validar las citas de cada requisito contra el texto fuente","evitar requisitos inventados o referencias inexistentes",
 ["Fragmento y localizador deben encontrarse o justificarse mediante una validación reproducible.",
  "Una alucinación de fuente bloquea el requisito automático.",
  "Los documentos se tratan como datos no confiables; instrucciones embebidas no cambian las reglas del sistema."]),
("HU-27","P0","MVP-10","Administrador","configurar el proveedor y los límites operativos de IA","controlar coste, repetición y tratamiento de información",
 ["Modelo, prompt, esquema y configuración quedan versionados sin contenido sensible en logs.",
  "Se limitan tokens, lotes, concurrencia, reintentos y llamadas repetidas por hash/versión.",
  "El envío de documentos internos exige autorización empresarial específica y secretos solo en backend."]),
("HU-28","P0","MVP-10","Analista","ver advertencias e incertidumbres de extracción","saber qué requisito necesita lectura humana",
 ["Se muestran ambigüedad, evidencia faltante, error de proveedor y posibles conflictos.",
  "La ausencia de salida del modelo no se interpreta como ausencia de requisitos.",
  "La evaluación real se diferencia de pruebas con mocks y reporta tamaño de muestra."]),
])

E7 = ("E7", "Comparación, revisión y aprobación humana",
      "Producir un borrador explicable y corregible, sin sustituir la decisión empresarial.",
      "MVP-11", [
("HU-29","P0","MVP-11","Sistema","comparar fechas, cantidades e indicadores con reglas deterministas","obtener resultados reproducibles para condiciones objetivas",
 ["Las reglas manejan límites, unidades, monedas, períodos y vigencias explícitos.",
  "Cada cálculo conserva entradas, regla, resultado y motivo.",
  "Valores faltantes o incompatibles pasan a revisión manual."]),
("HU-30","P0","MVP-11","Analista","comparar requisitos semánticos con evidencias de EAG","obtener una propuesta explicable para revisión",
 ["Se muestran por separado fuente del requisito y evidencia empresarial.",
  "No se afirma cumplimiento sin evidencia suficiente, vigente y compatible.",
  "Contradicciones, ambigüedad o soportes ilegibles quedan visibles."]),
("HU-31","P0","MVP-11","Analista","clasificar cada requisito con estados controlados","usar un lenguaje consistente y auditable",
 ["Solo se permiten cumple, cumple_parcialmente, no_cumple y revision_manual.",
  "Falta de evidencia no genera cumple ni no_cumple automáticamente.",
  "Cumple parcialmente solo aplica a un requisito divisible bajo criterio validado; mientras no exista, no se asigna automáticamente."]),
("HU-32","P0","MVP-11","Analista","revisar y corregir el borrador con justificación","resolver errores y dejar pendientes explícitos",
 ["Puede cambiar estado, evidencia u observación registrando autor, fecha y motivo.",
  "La salida automática inicial se conserva para medir discrepancias.",
  "Requisitos no aplicables permanecen en revision_manual hasta acordar evidencia y tratamiento."]),
("HU-33","P0","MVP-11","Aprobador autorizado","aprobar una versión concreta del análisis","habilitar el informe final solo después de revisión humana",
 ["La aprobación guarda usuario, fecha y versiones de expediente, perfil y análisis.",
  "Pendientes y limitaciones siguen visibles.",
  "Aprobar no equivale a postular, adjudicar ni decidir automáticamente participar."]),
("HU-34","P0","MVP-11","Sistema","invalidar la aprobación cuando cambien entradas o resultados","impedir que un informe use evidencia desactualizada",
 ["Cambios de documento, perfil, requisito, evidencia o decisión crean una nueva versión.",
  "La aprobación anterior deja de habilitar informe o envío.",
  "La interfaz explica qué cambió y qué revisión debe repetirse."]),
])

E8 = ("E8", "Informe y comunicación controlada",
      "Entregar un informe aprobado, trazable y seguro a destinatarios autorizados.",
      "MVP-12", [
("HU-35","P0","MVP-12","Analista","previsualizar el informe del análisis aprobado","verificar su contenido y presentación antes del envío",
 ["El informe identifica oportunidad, versión, aprobador, fecha, requisitos, evidencias y limitaciones.",
  "El backend bloquea el PDF final si la aprobación no está vigente.",
  "Tablas largas y caracteres españoles se renderizan sin recortes."]),
("HU-36","P0","MVP-12","Usuario autorizado","descargar el PDF final aprobado","conservar una salida legible sin exponer el expediente completo",
 ["La descarga exige permiso por recurso y usa almacenamiento privado.",
  "El PDF no añade afirmaciones sin evidencia ni adjunta soportes por defecto.",
  "La generación queda auditada con la versión correspondiente."]),
("HU-37","P0","MVP-12","Usuario autorizado","enviar el informe a destinatarios configurados","compartir el resultado sin duplicados ni envíos indiscriminados",
 ["Solo destinatarios autorizados pueden seleccionarse y el backend vuelve a validar aprobación.",
  "Una clave de idempotencia evita correos duplicados durante reintentos.",
  "Destino, estado e intentos quedan auditados sin contenido sensible; pruebas reales usan únicamente bandeja autorizada."]),
])

E9 = ("E9", "Retención, operación y recuperación",
      "Completar controles operativos antes de tratar documentos reales en producción.",
      "MVP-13", [
("HU-38","P0","MVP-13","Administrador","aplicar la política de retención a datos de oportunidad","eliminar oportunamente archivos, texto, análisis, informes y copias de trabajo",
 ["Un reloj controlado prueba el plazo configurado y el origen del cómputo.",
  "La purga cubre derivados y evita resurrección tras una restauración.",
  "El plazo propuesto de 30 días no se presenta como política definitiva hasta validación de EAG y backups."]),
("HU-39","P0","MVP-13","Equipo operador","monitorear tareas, fallos y alertas","detectar problemas sin registrar contenido empresarial",
 ["Se observan sincronización, extracción, IA, correo y colas fallidas con estados técnicos.",
  "Logs y alertas excluyen archivos, credenciales, tokens y fragmentos sensibles.",
  "Reintentos tienen límites y los fallos no se ocultan como éxito."]),
("HU-40","P0","MVP-13","Equipo operador","restaurar backups y ejecutar rollback probado","recuperar el servicio respetando accesos y purgas",
 ["Staging exige autenticación y no expone claves privilegiadas ni buckets públicos.",
  "Se ensayan restauración y rollback con evidencia reproducible.",
  "La restauración reaplica tombstones o purgas pendientes."]),
("HU-41","P0","MVP-13","Responsable empresarial","autorizar el tratamiento de datos y proveedores externos","decidir conscientemente qué información puede procesarse",
 ["Se documentan finalidad, datos enviados, retención y controles del proveedor.",
  "No se contratan ni configuran servicios pagos sin autorización específica.",
  "store=false no se presenta por sí solo como retención cero."]),
])

E10 = ("E10", "Piloto, medición y decisión de lanzamiento",
      "Validar utilidad, calidad y riesgos con usuarios y datos autorizados antes de cerrar el MVP.",
      "MVP-14", [
("HU-42","P0","MVP-14","Responsable del piloto","comparar el análisis manual y asistido sobre las mismas entradas","medir tiempo y errores sin sesgos evitables",
 ["Se fijan previamente muestra, versiones, referencia humana, alcance y umbrales.",
  "Se miden por separado tiempo transcurrido, procesamiento, revisión, corrección y trabajo humano.",
  "Se reportan tamaño de muestra, denominadores, fallos y falsos cumplimientos; 60% no es garantía ni resultado demostrado."]),
("HU-43","P0","MVP-14","Analista y administrador","ejecutar UAT y recibir un manual breve","confirmar que el flujo puede operarse de forma segura",
 ["El recorrido extremo a extremo usa usuarios y datos autorizados.",
  "Incidencias, capacitación y aceptación o rechazo se registran con responsables.",
  "Si faltan datos o usuarios, se entrega el protocolo pero el piloto sigue pendiente."]),
("HU-44","P0","MVP-14","Gerencia","tomar una decisión go/no-go basada en evidencia","evitar lanzar con riesgos críticos o calidad insuficiente",
 ["La decisión incluye métricas, limitaciones, incidencias y pendientes.",
  "Falsos cumplimientos o riesgos críticos de seguridad no resueltos bloquean el lanzamiento.",
  "La revisión humana final queda registrada; el sistema no decide autónomamente participar en una licitación."]),
])

EPICAS = [E1, E2, E3, E4, E5, E6, E7, E8, E9, E10]

PENDIENTES = [
 ("Muestra real autorizada y documentos mínimos del perfil","HU-20 a HU-34, HU-42","Comercial, áreas aportantes y Gerencia"),
 ("Cobertura real de pliegos y relación entre datasets SECOP","HU-05, HU-11, HU-15","Equipo técnico + Comercial"),
 ("Horario y ventana incremental","HU-07","Administrador / operación"),
 ("Límites de 50 MB por archivo y 300 MB por oportunidad","HU-13, HU-16","EAG + equipo técnico"),
 ("Criterios por tipo para cumple parcialmente y no aplica","HU-31, HU-32","Comercial y áreas competentes"),
 ("Personas o roles autorizados para aprobar y enviar","HU-33 a HU-37","Gerencia"),
 ("Inicio del plazo de 30 días, maestros, auditoría y backups","HU-38, HU-40","Gerencia + legal/operación"),
 ("Proveedor de IA, datos permitidos, retención y presupuesto","HU-27, HU-41","Gerencia + responsable de datos"),
 ("Umbrales, tamaño de muestra y criterio go/no-go","HU-42 a HU-44","Gerencia + revisor designado"),
]

EXCLUSIONES = [
 "Postulación automática de ofertas o decisión autónoma de participar.",
 "Garantía de adjudicación, precisión no medida o reducción de tiempo presentada como resultado.",
 "Fuentes distintas de SECOP II en la primera versión.",
 "Registro manual de oportunidades; la carga manual se limita a documentos complementarios de una oportunidad SECOP II.",
 "WhatsApp, Telegram, facturación, aplicación móvil y personalizaciones avanzadas.",
 "Buckets públicos, enlaces permanentes, expedientes completos adjuntos por defecto o contenido sensible en observabilidad.",
 "Uso de documentos internos con un proveedor externo sin autorización empresarial específica.",
]

FLOW = [
 ("SECOP II","Sincronización y detalle de oportunidades oficiales"),
 ("Expediente","Documentos con origen, versión y cuarentena"),
 ("Extracción","Texto y OCR trazables por localizador"),
 ("Requisitos","Extracción estructurada con IA y citas validadas"),
 ("Perfil EAG","Evidencias empresariales versionadas"),
 ("Comparación","Propuesta explicable y corregible"),
 ("Revisión","Estados controlados y justificación"),
 ("Aprobación","Solo después de revisión humana"),
 ("PDF","Informe aprobado y trazable"),
 ("Correo autorizado","Solo a destinatarios configurados"),
]

ACTORS = [
 ("Analista","ROL OPERATIVO","Busca oportunidades, reúne documentos, revisa requisitos, corrige resultados y prepara el borrador.",
  '<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 3.6-6 8-6s8 2 8 6"/>'),
 ("Administrador","ROL DE GESTIÓN","Gestiona acceso, configuración compartida, perfil empresarial y operación autorizada.",
  '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 1 1-4 0v-.09a1.65 1.65 0 0 0-1-1.51 1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 1 1 0-4h.09a1.65 1.65 0 0 0 1.51-1 1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33h.01a1.65 1.65 0 0 0 1-1.51V3a2 2 0 1 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82v.01a1.65 1.65 0 0 0 1.51 1H21a2 2 0 1 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/>'),
 ("Aprobador / Gerencia","ROL DECISOR","Aprueba una versión del análisis y toma la decisión empresarial. Su designación exacta está pendiente.",
  '<path d="M9 12l2 2 4-4"/><circle cx="12" cy="12" r="9"/>'),
 ("Sistema / Equipo operador","ROL TÉCNICO","Ejecuta procesos controlados y mantiene seguridad, trazabilidad, retención y recuperación.",
  '<rect x="2" y="4" width="20" height="14" rx="2"/><path d="M8 21h8M12 18v3"/>'),
]
